name: "pull request tests"

on:
  pull_request:
    branches: [ main ]

jobs:
  packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.get_package_list.outputs.packages }}
    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: "get package list"
        id: get_package_list
        uses: ./.github/actions/get_package_list

  test_packages_amd64:
    needs: packages
    uses: ./.github/workflows/test_packages.yml
    with:
      packages: ${{ needs.packages.outputs.packages }}
      arch: amd64
  
  test_packages_arm64:
    needs: packages
    uses: ./.github/workflows/test_packages.yml
    with:
      packages: ${{ needs.packages.outputs.packages }}
      arch: arm64
      runner: ubuntu-latest-arm64
